### ISSUE TITLE
unable to use in ejected react-native app

### ISSUE THREAD

**Issue by noahehall** [ThakurBallary/react-native-btr#1]
bundling failed: Error: Unable to resolve module `@expo/vector-icons` from `/home/imsov/git/d4d/no
de_modules/react-native-btr/src/Components/CheckBox.js`: Module `@expo/vector-icons` does not exist in th
e Haste module map

**Comment by cobarx** [comment]
Changing the import to:
```
import Icon from 'react-native-vector-icons/MaterialIcons';
```

appears to fix this. Haven't had time to thoroughly test and create a PR.

**Comment by ThakurBallary** [comment]
Hi @noahehall 

This package is built using expo and vector-icons are already available in expo. So, we didn't include react-native-vector-icons as dependency.

As @cobarx mentioned a fix to the issue, I'm closing this thread.

Please feel free to open the issue back if you think this has to be included in the package.

**Comment by cobarx** [comment]
Hi @ThakurBallary, I think supporting non-Expo projects would be a good idea. I have a UI library that I'm hoping to open source. Currently I'm using react-native-btr for my checkboxes, but other people can't be expected to go in and change the source code for react-native-btr just to use my library.

Can we use some kind of import that works on both Expo & non-Expo? This is the best checkbox implementation I've found and it would be great to bring it to a wider audience.

**Comment by cobarx** [comment]
@ThakurBallary I tested and if we use the syntax I mentioned, it works fine in Expo as well. Therefore, I don't see any drawbacks to supporting non-Expo projects as well.

I have submitted PR #6 to make this change available to everyone.
