### ISSUE TITLE
problem importing some components

### ISSUE THREAD

**Issue by mvolkmann** [ThakurBallary/react-native-btr#13]
It seems that all the components that are implemented as function components can be imported like this:

```js
import {CheckBox, ColorPicker} from 'react-native-btr';
```

But all the components that are implemented with classes cannot be imported like this:

```js
import {CollapsibleCard, RadioGroup, SnackBar} from 'react-native-btr';
```
It says these imports are not found.
Is there another way I can use them?

**Comment by ThakurBallary** [comment]
importing type depends on the way of exporting, like **export default** or **export**  
FYI its not related to function or class component.

Here is the working link [react-native-btr-demo](https://expo.io/@thakurballary/react-native-btr-demo)
