### ISSUE TITLE
Unrecognized font family 'Material Icons'

### ISSUE THREAD

**Issue by gfrileux** [ThakurBallary/react-native-btr#14]
Hi,

I am currently trying to use the CheckBox component. However when I import it into the project, I get this error: 
`Unrecognized font family 'Material Icons'`

Here is our package.json: 

    "react": "16.10.2",
    "react-native": "0.61.2",
    "react-native-btr": "^1.1.4",

We do not have the vector-icon library installed directly in our package.json but I understand it's not needed right ?

This happens on the iOS Simulator, I have not tried Android yet.

Does the react-native-vector-icons library need to be installed manually in the project ?

Thanks
Greg

**Comment by ThakurBallary** [comment]
Please update the package and try. Here is the link to working demo.
[react-native-btr-demo](https://expo.io/@thakurballary/react-native-btr-demo)
