### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by srithar21** [ThakurBallary/react-native-btr#17]
Hi,

I am using the 2.1.2 version of this library.

But recently got security issue because of lodash@4.5.0.
react-native-btr@2.1.2 › react-native-vector-icons@8.1.0 › lodash.template@4.5.0

Can you please resolve this issue?. This issue will be resolved If you upgrade into react-native-vector-icons@9.1.0

https://security.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

**Comment by ThakurBallary** [comment]
[Fixed](https://github.com/ThakurBallary/react-native-btr/commit/b780fffb338c40120e53098e3b425a08574fe0fa)
