### ISSUE TITLE
EventEmitter.removeListener('didUpdateDimensions', ...): Method has been deprecated

### ISSUE THREAD

**Issue by Faisals3** [ThakurBallary/react-native-btr#18]
Hello

I am getting the following warning :

EventEmitter.removeListener('didUpdateDimensions', ...): Method has been deprecated. Please instead use remove() on the subscription returned by EventEmitter.addListener.

when I used the bottom sheet component

any idea or help how to avoid it ? I think it's related to the component it self and how it's built

**Comment by ThakurBallary** [comment]
@Faisals3 thanks for writing. This issue is fixed in v2.1.4
