### ISSUE TITLE
Outer circle of radio btn has some gliches (doesn't have smooth appearance)

### ISSUE THREAD

**Issue by bbeckk** [ThakurBallary/react-native-btr#2]
The outer circle when the btn is selected or not doesn't have smooth circle. Please see the inner circle of the selected radio btn (value is different labelled btn in the image below) which looks very smooth in appearance.

P.S I've tested it in android samsung devices.

![screenshot_20180831-131152](https://user-images.githubusercontent.com/13558880/44903110-6127d700-ad2b-11e8-8941-97352ce99c34.png)

**Comment by ThakurBallary** [comment]
Fixed in [react-native-radio-buttons-group](https://github.com/ThakurBallary/react-native-radio-buttons-group)
