### ISSUE TITLE
Add Fontawesome Icons to IconPicker

### ISSUE THREAD

**Issue by HamzaAitOumghar** [ThakurBallary/react-native-btr#20]
Hi ,
is there is any possibility to add fontawesome  icons to IconPicker ?

**Comment by ThakurBallary** [comment]
Hi

Thanks for writing!!

Please upgrade to v2.2.0 and have a look at [IconPicker Docs](https://github.com/ThakurBallary/react-native-btr/blob/main/docs/ICON_PICKER.md) to know how to achieve it.

Output: [Open on Expo Go](https://expo.io/@thakurballary/react-native-btr-demo) :iphone:
